name: Boomi CICD Deployments

# on:
#   push:
#     branches:

 
on:
  pull_request:
    types:
      - opened


jobs:
  development:
    name: Development Deployment
    runs-on: ubuntu-latest  # self-hosted
    environment: development
 
    env:
      BOOMI_ENVIRONMENT_NAME: "Test Cloud Environment"
      BOOMI_ATOM_NAME: "Test Atom Cloud"
      BOOMI_ACCOUNT_ID: ${{ vars.BOOMI_ACCOUNT_ID }}
      BOOMI_BASE_URL: ${{ vars.BOOMI_BASE_URL }}
      BOOMI_USERNAME: ${{ vars.BOOMI_USERNAME }}
      BOOMI_PASSWORD: ${{ secrets.BOOMI_PASSWORD }}
      BOOMI_RELEASE_FILE: "boomi-cicd-release/boomi_release/release.json"
      GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      ISSUE_NUMBER: ${{ github.event.number }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
      
# Writing annotation messages: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-a-notice-message

      # - name: 'Write a notice message'
      #   run: |
      #     echo "::notice title='Automated Testing Skipped'::Missing semicolon"


      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Checkout current Boomi release repo
        uses: actions/checkout@v4
        with:
          path: boomi-cicd-release

      # Runner must have read/write access
      - name: Comment PR 
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀🚀🚀 Opening deployment doors!🚀🚀🚀'
            })

      - name: Checkout Boomi CICD Library
        uses: actions/checkout@v4
        with:
          repository: sivasuchavali/Boomi_CICD_Demo
          token: ${{ secrets.BOOMI_CICD_LIBRARY_PAT }}
          path: boomi-cicd-cli-py

      - name: Install dependencies
        run: |
          cd ${GITHUB_WORKSPACE}/boomi-cicd-cli-py
          pip install -r ./requirements.txt

      - name: Deployment
        run: | 
          cd ${GITHUB_WORKSPACE}/boomi-cicd-cli-py
          export PYTHONPATH=$(pwd)
          export BOOMI_RELEASE_FILE=${GITHUB_WORKSPACE}/${BOOMI_RELEASE_FILE}
          python3.11 boomi_cicd/scripts/github_automated_testing.py


  stage:
    name: Stage Deployment
    runs-on: ubuntu-latest  # self-hosted
    needs: development

    environment: stage

    env:
      BOOMI_ENVIRONMENT_NAME: "ADO Stage"
      BOOMI_ACCOUNT_ID: ${{ vars.BOOMI_ACCOUNT_ID }}
      BOOMI_BASE_URL: ${{ vars.BOOMI_BASE_URL }}
      BOOMI_USERNAME: ${{ vars.BOOMI_USERNAME }}
      BOOMI_PASSWORD: ${{ secrets.BOOMI_PASSWORD }}
      BOOMI_RELEASE_FILE: "boomi-cicd-release/boomi_release/release.json"
      

    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Checkout current Boomi release repo
        uses: actions/checkout@v4
        with:
          path: boomi-cicd-release

      - name: Checkout Boomi CICD Library
        uses: actions/checkout@v4
        with:
          repository: sivasuchavali/Boomi_CICD_Demo
          token: ${{ secrets.BOOMI_CICD_LIBRARY_PAT }}
          path: boomi-cicd-cli-py

      - name: Install dependencies
        run: |
          cd ${GITHUB_WORKSPACE}/boomi-cicd-cli-py
          pip install -r ./requirements.txt

      - name: Deployment
        run: | 
          cd ${GITHUB_WORKSPACE}/boomi-cicd-cli-py
          export PYTHONPATH=$(pwd)
          export BOOMI_RELEASE_FILE=${GITHUB_WORKSPACE}/${BOOMI_RELEASE_FILE}
          python3.11 boomi_cicd/scripts/release_pipeline.py


  production:
    name: Production Deployment
    runs-on: ubuntu-latest  # self-hosted
    needs: [development, stage]

    environment: production

    env:
      BOOMI_ENVIRONMENT_NAME: "ADO Production"
      BOOMI_ACCOUNT_ID: ${{ vars.BOOMI_ACCOUNT_ID }}
      BOOMI_BASE_URL: ${{ vars.BOOMI_BASE_URL }}
      BOOMI_USERNAME: ${{ vars.BOOMI_USERNAME }}
      BOOMI_PASSWORD: ${{ secrets.BOOMI_PASSWORD }}
      BOOMI_RELEASE_FILE: "boomi-cicd-release/boomi_release/release.json"

    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Checkout current Boomi release repo
        uses: actions/checkout@v4
        with:
          path: boomi-cicd-release

      - name: Checkout Boomi CICD Library
        uses: actions/checkout@v4
        with:
          repository: sivasuchavali/Boomi_CICD_Demo
          token: ${{ secrets.BOOMI_CICD_LIBRARY_PAT }}
          path: boomi-cicd-cli-py

      - name: Install dependencies
        run: |
          cd ${GITHUB_WORKSPACE}/boomi-cicd-cli-py
          pip install -r ./requirements.txt

      - name: Deployment
        run: | 
          cd ${GITHUB_WORKSPACE}/boomi-cicd-cli-py
          export PYTHONPATH=$(pwd)
          export BOOMI_RELEASE_FILE=${GITHUB_WORKSPACE}/${BOOMI_RELEASE_FILE}
          python3.11 boomi_cicd/scripts/release_pipeline.py
